//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musher_Table
    {
        public int MusherNumber { get; set; }
        public string MusherName { get; set; }
        public int Category { get; set; }
    
        public virtual Category_Table Category_Table { get; set; }
    }
}
